language: python
python:
  - "3.7"
branches:
  only:
  - master

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - echo "SECRET_KEY=key1234" >> .env && echo "ALLOWED_HOSTS=*" >> .env
script:
  - python manage.py test apps